import type { Journey, JourneyPackage, JourneyStop, JourneyVia } from './v2/journeyModel'

const COUNTRY_NB: Record<string, string> = {
  italy: 'Italia',
  italien: 'Italia',
  italia: 'Italia',
  spain: 'Spania',
  spanien: 'Spania',
  españa: 'Spania',
  espana: 'Spania',
  spania: 'Spania',
  france: 'Frankrike',
  frankreich: 'Frankrike',
  frankrike: 'Frankrike',
  norway: 'Norge',
  norwegen: 'Norge',
  norge: 'Norge',
  sweden: 'Sverige',
  schweden: 'Sverige',
  sverige: 'Sverige',
  denmark: 'Danmark',
  dänemark: 'Danmark',
  danmark: 'Danmark',
  finland: 'Finland',
  finnland: 'Finland',
  iceland: 'Island',
  island: 'Island',
  germany: 'Tyskland',
  deutschland: 'Tyskland',
  tyskland: 'Tyskland',
  austria: 'Østerrike',
  österreich: 'Østerrike',
  osterreich: 'Østerrike',
  østerrike: 'Østerrike',
  switzerland: 'Sveits',
  schweiz: 'Sveits',
  suisse: 'Sveits',
  sveits: 'Sveits',
  netherlands: 'Nederland',
  nederland: 'Nederland',
  holland: 'Nederland',
  belgium: 'Belgia',
  belgien: 'Belgia',
  belgique: 'Belgia',
  belgia: 'Belgia',
  'united kingdom': 'Storbritannia',
  'great britain': 'Storbritannia',
  england: 'England',
  scotland: 'Skottland',
  ireland: 'Irland',
  irland: 'Irland',
  portugal: 'Portugal',
  greece: 'Hellas',
  griechenland: 'Hellas',
  hellas: 'Hellas',
  croatia: 'Kroatia',
  kroatien: 'Kroatia',
  kroatia: 'Kroatia',
  slovenia: 'Slovenia',
  slovakia: 'Slovakia',
  'czech republic': 'Tsjekkia',
  czechia: 'Tsjekkia',
  tschechien: 'Tsjekkia',
  tsjekkia: 'Tsjekkia',
  poland: 'Polen',
  polen: 'Polen',
  hungary: 'Ungarn',
  ungarn: 'Ungarn',
  romania: 'Romania',
  bulgaria: 'Bulgaria',
  serbia: 'Serbia',
  turkey: 'Tyrkia',
  türkiye: 'Tyrkia',
  tyrkia: 'Tyrkia',
  cyprus: 'Kypros',
  zypern: 'Kypros',
  kypros: 'Kypros',
  estonia: 'Estland',
  estland: 'Estland',
  latvia: 'Latvia',
  lithuania: 'Litauen',
  litauen: 'Litauen',
  ukraine: 'Ukraina',
  ukraina: 'Ukraina',
  russia: 'Russland',
  russland: 'Russland',
  'united states': 'USA',
  'united states of america': 'USA',
  usa: 'USA',
  brazil: 'Brasil',
  brasilien: 'Brasil',
  brasil: 'Brasil',
  egypt: 'Egypt',
  morocco: 'Marokko',
  marokko: 'Marokko',
  'south africa': 'Sør-Afrika',
  'united arab emirates': 'De forente arabiske emirater',
  china: 'Kina',
  kina: 'Kina',
  'south korea': 'Sør-Korea',
  philippines: 'Filippinene',
  filippinene: 'Filippinene',
}

const CITY_NB: Record<string, string> = {
  rome: 'Roma',
  roma: 'Roma',
  milan: 'Milano',
  milano: 'Milano',
  florence: 'Firenze',
  firenze: 'Firenze',
  venice: 'Venezia',
  venedig: 'Venezia',
  venezia: 'Venezia',
  naples: 'Napoli',
  neapel: 'Napoli',
  napoli: 'Napoli',
  turin: 'Torino',
  torino: 'Torino',
  genoa: 'Genova',
  genua: 'Genova',
  genova: 'Genova',
  padua: 'Padova',
  padova: 'Padova',
  syracuse: 'Siracusa',
  seville: 'Sevilla',
  sevilla: 'Sevilla',
  majorca: 'Mallorca',
  mallorca: 'Mallorca',
  copenhagen: 'København',
  kopenhagen: 'København',
  københavn: 'København',
  gothenburg: 'Göteborg',
  göteborg: 'Göteborg',
  helsinki: 'Helsingfors',
  helsingfors: 'Helsingfors',
  brussels: 'Brussel',
  brüssel: 'Brussel',
  bruxelles: 'Brussel',
  brussel: 'Brussel',
  antwerp: 'Antwerpen',
  'the hague': 'Haag',
  'den haag': 'Haag',
  haag: 'Haag',
  munich: 'München',
  münchen: 'München',
  cologne: 'Köln',
  köln: 'Köln',
  nuremberg: 'Nürnberg',
  nürnberg: 'Nürnberg',
  vienna: 'Wien',
  wien: 'Wien',
  geneva: 'Genève',
  genf: 'Genève',
  genève: 'Genève',
  zurich: 'Zürich',
  zürich: 'Zürich',
  prague: 'Praha',
  prag: 'Praha',
  praha: 'Praha',
  warsaw: 'Warszawa',
  warschau: 'Warszawa',
  warszawa: 'Warszawa',
  krakow: 'Kraków',
  cracow: 'Kraków',
  athens: 'Athen',
  athen: 'Athen',
  lisbon: 'Lisboa',
  lissabon: 'Lisboa',
  lisboa: 'Lisboa',
  moscow: 'Moskva',
  moskau: 'Moskva',
  moskva: 'Moskva',
  cairo: 'Kairo',
  kairo: 'Kairo',
  marseilles: 'Marseille',
  lyons: 'Lyon',
}

export function localizeCountry(name?: string | null): string {
  const raw = (name || '').trim()
  if (!raw) return ''
  return COUNTRY_NB[raw.toLowerCase()] || raw
}

export function localizeCity(name?: string | null): string {
  const raw = (name || '').trim()
  if (!raw) return ''
  return CITY_NB[raw.toLowerCase()] || raw
}

function localizePack(pack: JourneyPackage): JourneyPackage {
  return {
    ...pack,
    basePlace: localizeCity(pack.basePlace) || pack.basePlace,
    baseCountry: localizeCountry(pack.baseCountry) || pack.baseCountry,
    days: (pack.days || []).map((d) => ({
      ...d,
      city: localizeCity(d.city) || d.city,
      country: localizeCountry(d.country) || d.country,
    })),
  }
}

function localizeStop(stop: JourneyStop): JourneyStop {
  return {
    ...stop,
    city: localizeCity(stop.city) || stop.city,
    country: localizeCountry(stop.country) || stop.country,
    pack: stop.pack ? localizePack(stop.pack) : stop.pack,
    cruise: stop.cruise ? localizePack(stop.cruise) : stop.cruise,
    sights: (stop.sights || []).map((s) => ({
      ...s,
      title: localizeCity(s.title) || s.title,
    })),
  }
}

function localizeVia(via: JourneyVia): JourneyVia {
  return {
    ...via,
    title: localizeCity(via.title) || via.title,
    country: localizeCountry(via.country) || via.country,
    sights: (via.sights || []).map((s) => ({
      ...s,
      title: localizeCity(s.title) || s.title,
    })),
  }
}

/** Show and persist place names in Norwegian. */
export function localizeJourneyPlaces(journey: Journey): Journey {
  return {
    ...journey,
    stops: (journey.stops || []).map(localizeStop),
    legs: (journey.legs || []).map((leg) => ({
      ...leg,
      vias: (leg.vias || []).map(localizeVia),
    })),
  }
}
